
[general]
	#Colors must be specified in #RRGGBB format
	"health color values" = ["#FF1313", "#FFFF13", "#13FF13", "#0C9DF1", "#B486FF", "#EDEDED"]
	#Colors must be specified in #RRGGBB format
	"absorption color values" = ["#E5CE00", "#00DA00", "#7713FF"]
	#Description level of text, all shows total health and absorption bars, bars shows number of bars, none doesn't show text
	#Allowed Values: NONE, BARS, ALL
	"show bars" = "ALL"
	#Size of index number
	#Range: 0.0 ~ 1.0
	"text size" = 0.75

