
[general]
	#Colors must be specified in #RRGGBB format
	"color values" = ["#FFFFFF", "#27FFE3", "#7F00FF"]
	#Always show armor bar even if empty?
	"Always show bar" = false
	#Show empty armor icons?
	"Show empty icons" = false

